### ISSUE TITLE
Unable to make phone calls to mobile pumpkin

### ISSUE THREAD

**Issue by desertigloo** [raspberry-pumpkins/clustered-pi#1]
Hi I tried to make a phone call from my home pumpkin to my mobile pumpkin and got an error. I don't know what the error is cause i'm an end user.

pls fix i'm waiting for a call at 5:20PM on my mobile pumpkin line.

**Comment by haggy** [comment]
Hello Mr Igloo,

```
The pumpkin phone will be coming in a future release/repo. Please stand by for exciting times.
```

**Comment by desertigloo** [comment]
👎
